services:
  adguard-home:
    image: adguard/adguardhome
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 80:80/tcp
    - 443:443/tcp
    restart: unless-stopped
    volumes:
    - ./AdGuardHome/data:/opt/adguardhome/work
    - ./AdGuardHome/conf:/opt/adguardhome/conf
version: '3.3'
