services:
  jackett:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/Chicago
    image: linuxserver/jackett:latest
    ports:
    - 9117/tcp
    volumes:
    - /config
    - /downloads
version: '3.3'
