services:
  nginx proxy manager v2 with sqllite:
    image: jc21/nginx-proxy-manager:latest
    ports:
    - 80:80/tcp
    - 81:81/tcp
    - 443:443/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/nginx-proxy-manager/data
      container: /data
    - bind: /portainer/Files/AppData/Config/nginx-proxy-manager/letsencrypt
      container: /etc/letsencrypt
version: '3.3'
