services:
  quassel-core:
    image: linuxserver/quassel-core:latest
    ports:
      - "4242:4242/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/Quassel-core:/config"
    restart: unless-stopped