services:
  adguard:
    image: adguard/adguardhome:latest
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
    - 68:68/tcp
    - 68:68/udp
    - 80:80/tcp
    - 443:443/tcp
    - 853:853/tcp
    - 3000:3000/tcp
    volumes:
    - bind: /portainer/Files/AppData/Adguard/Workdir
      container: /opt/adguardhome/work
    - bind: /portainer/Files/AppData/Adguard/Conf
      container: /opt/adguardhome/conf
version: '3.3'
