services:
  transmission:
    image: linuxserver/transmission:latest
    ports:
      - "9091:9091/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/Transmission:/config"
    restart: unless-stopped