services:
  homer:
    image: b4bz/homer:latest
    ports:
    - 8902:8080/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/Homer/assets
      container: /www/assets
    - bind: /portainer/Files/AppData/Config/Homer
      container: /www/config.yml
version: '3.3'
