services:
  trilium:
    image: zadam/trilium:latest
    ports:
    - 3388:8080/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/trilium-data
      container: /home/node/trilium-data
version: '3.3'
