services:
  trilium:
    image: zadam/trilium:latest
    ports:
      - "3388:8080/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/trilium-data:/home/node/trilium-data"
    restart: unless-stopped