services:
  code-server:
    image: linuxserver/code-server:latest
    ports:
      - "8443:8443/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/Code-Server:/config"
    restart: unless-stopped