services:
  scrutiny:
    image: analogj/scrutiny:latest
    ports:
    - 8080/tcp
    volumes:
    - bind: /opt/mediadepot/apps/scrutiny
      container: /scrutiny/config/
    - bind: /run/udev
      container: /run/udev
      readonly: true
version: '3.3'
