services:
  htpcmanager:
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/Chicago
    image: linuxserver/htpcmanager:latest
    ports:
    - 8085/tcp
    volumes:
    - /config
version: '3.3'
