services:
  htpcmanager:
    image: linuxserver/htpcmanager:latest
    ports:
      - "8085:8085/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/HTPCmanager:/config"
    restart: unless-stopped