services:
  quassel irc:
    image: linuxserver/quassel-core:latest
    ports:
    - 4242:4242/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/Quassel-core
      container: /config
version: '3.3'
