services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    ports:
      - "6881:6881/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/qBittorrent:/config"
    restart: unless-stopped