services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    ports:
    - 9091:9091/tcp
    volumes:
    - bind: /portainer/Downloads
      container: /data
    - bind: /etc/localtime
      container: /etc/localtime
version: '3.3'
