services:
  protonmail bridge:
    image: shenxn/protonmail-bridge:latest
    ports:
    - 143/tcp
    - 25/tcp
    volumes:
    - bind: /portainer/Files/AppData/ProtonMail-Bridge
      container: /root
version: '3.3'
