services:
  protonmail-bridge:
    image: shenxn/protonmail-bridge:latest
    ports:
      - "143/tcp"
    volumes:
      - "/portainer/Files/AppData/ProtonMail-Bridge:/root"
    restart: unless-stopped