services:
  couchpotato:
    image: linuxserver/couchpotato:latest
    ports:
      - "5050:5050/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/Couchpotato:/config"
    restart: unless-stopped