services:
  headphones:
    image: linuxserver/headphones:latest
    ports:
      - "8181:8181/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/Headphones:/config"
    restart: unless-stopped