services:
  openvpn access server:
    image: linuxserver/openvpn-as:latest
    ports:
    - 943:943/tcp
    - 9443:9443/tcp
    - 1194:1194/udp
    volumes:
    - bind: /portainer/Files/AppData/Config/OpenVPN-AS
      container: /config
version: '3.3'
