services:
  pure-ftp server:
    image: stilliard/pure-ftpd:hardened
    ports:
    - 21/tcp
    - 30000/tcp
    - 30001/tcp
    - 30002/tcp
    - 30003/tcp
    - 30004/tcp
    - 30005/tcp
    - 30006/tcp
    - 30007/tcp
    - 30008/tcp
    - 30009/tcp
    volumes:
    - bind: /opt/mediadepot/apps/pureftp
      container: /etc/pure-ftpd/passwd
    - bind: /media/storage/tvshows
      container: /data/tvshows
    - bind: /media/storage/movies
      container: /data/movies
    - bind: /media/storage/music
      container: /data/music
    - bind: /media/storage/ebooks
      container: /data/ebooks
    - bind: /media/storage/photos
      container: /data/photos
    - bind: /media/storage/documents
      container: /data/documents
    - bind: /media/storage/downloads
      container: /data/downloads
    - bind: /media/storage/software
      container: /data/software
    - bind: /media/temp/blackhole
      container: /data/blackhole
    - bind: /media/temp/processing
      container: /data/processing
version: '3.3'
