services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    ports:
    - 9696:9696/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/Prowlarr
      container: /config
version: '3.3'
