services:
  changedetection:
    image: dgtlmoon/changedetection.io
    ports:
      - "No ports provided"
    volumes:
      - "/portainer/Files/AppData/Config/changedetection:/datastore"
    restart: always