services:
  musicbrainz:
    image: linuxserver/musicbrainz:latest
    ports:
      - "5000:5000/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/MusicBrainz:/config"
    restart: unless-stopped