services:
  tiddlywiki:
    image: mazzolino/tiddlywiki:latest
    ports:
      - "8080:8080/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/TiddlyWiki:/var/lib/tiddlywiki"
    restart: unless-stopped