services:
  filebrowser:
    image: 80x86/filebrowser:latest
    ports:
    - 8082:8082/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/FileBrowser
      container: /config
    - bind: /portainer/Files/AppData/Config
      container: /myfiles
version: '3.3'
