services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    ports:
    - 8096:8096/tcp
    - 8920:8920/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/Jellyfin
      container: /config
    - bind: /portainer/TV
      container: /data/tvshows
    - bind: /portainer/Movies
      container: /data/movies
version: '3.3'
