services:
  xbackbone:
    image: linuxserver/xbackbone:latest
    ports:
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    - bind: /volume1/docker/xbackbone/config
      container: /config
version: '3.3'
