services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    ports:
    - 8080/tcp
    - 9090/tcp
    volumes:
    - container: /config
    - container: /downloads
    - container: /incomplete-downloads
version: '3.3'
