services:
  freecad:
    image: linuxserver/freecad:latest
    ports:
    - 3000:3000/tcp
    - 3001:3001/tcp
    volumes:
    - bind: /volume1/docker/freecad/config
      container: /config
version: '3.3'
