services:
  wireguard:
    image: linuxserver/wireguard:latest
    ports:
    - 51820:51820/udp
    volumes:
    - bind: /volume1/docker/wireguard/config
      container: /config
    - bind: /lib/modules
      container: /lib/modules
version: '3.3'
