services:
  contentbox:
    image: ortussolutions/contentbox:latest
    ports:
    - 8080/tcp
    - 8443/tcp
    volumes:
    - container: /data/contentbox/db
    - container: /app/includes/shared/media
version: '3.3'
