services:
  revealjs:
    image: cloudogu/reveal.js
    ports:
      - "6060:8080/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/revealjs/docs/slides:/reveal/docs/slides"
    restart: always