services:
  snibox:
    image: snowmean/snibox-sqlite:latest
    ports:
    - 3010:3000/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/Snibox
      container: /app/db/database
version: '3.3'
