services:
  kavita:
    image: kizaing/kavita:latest
    ports:
    - 5000/tcp
    volumes:
    - bind: /portainer/Books
      container: /books
    - bind: /portainer/Files/AppData/Config/kavita
      container: /config
version: '3.3'
