services:
  syslog-ng:
    image: linuxserver/syslog-ng:latest
    ports:
    - 514:5514/udp
    - 601:6601/tcp
    - 6514:6514/tcp
    volumes:
    - bind: /volume1/docker/syslog-ng/config
      container: /config
    - bind: /var/log
      container: /var/log
version: '3.3'
