services:
  unifi video:
    image: pducharme/unifi-video-controller:latest
    ports:
    - 1935:1935/tcp
    - 7444:7444/tcp
    - 7447:7447/tcp
    - 6666:6666/tcp
    - 7442:7442/tcp
    - 7080:7080/tcp
    - 7443:7443/tcp
    - 7445:7445/tcp
    - 7446:7446/tcp
    volumes:
    - bind: /portainer/Files/AppData/Config/UnifFiVideo/Recordings/
      container: /recordings
    - bind: /portainer/Files/AppData/Config/UniFiVideo/
      container: /config
version: '3.3'
