services:
  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    ports:
      - "6595:6595/tcp"
    volumes:
      - "/portainer/Files/AppData/Config/DeeMix:/config"
    restart: unless-stopped