services:
  zotero:
    image: linuxserver/zotero:latest
    ports:
    - 3000:3000/tcp
    - 3001:3001/tcp
    volumes:
    - bind: /volume1/docker/zotero/config
      container: /config
version: '3.3'
