services:
  unifi-controller:
    image: linuxserver/unifi-controller:latest
    ports:
      - "3478:3478/udp"
    volumes:
      - "/portainer/Files/AppData/Config/Unifi:/config"
    restart: unless-stopped